<?php

declare(strict_types=1);

namespace App\Services;

class CountryService
{
    /**
     * Get a list of timezones with their UTC offsets and names.
     */
    public function getCountries(): array
    {
        return [
            ['value' => 'AF', 'label' => 'Afghanistan'],
            ['value' => 'AL', 'label' => 'Albania'],
            ['value' => 'DZ', 'label' => 'Algeria'],
            ['value' => 'AS', 'label' => 'American Samoa'],
            ['value' => 'AD', 'label' => 'Andorra'],
            ['value' => 'AO', 'label' => 'Angola'],
            ['value' => 'AI', 'label' => 'Anguilla'],
            ['value' => 'AQ', 'label' => 'Antarctica'],
            ['value' => 'AG', 'label' => 'Antigua and Barbuda'],
            ['value' => 'AR', 'label' => 'Argentina'],
            ['value' => 'AM', 'label' => 'Armenia'],
            ['value' => 'AW', 'label' => 'Aruba'],
            ['value' => 'AU', 'label' => 'Australia'],
            ['value' => 'AT', 'label' => 'Austria'],
            ['value' => 'AZ', 'label' => 'Azerbaijan'],
            ['value' => 'BS', 'label' => 'Bahamas'],
            ['value' => 'BH', 'label' => 'Bahrain'],
            ['value' => 'BD', 'label' => 'Bangladesh'],
            ['value' => 'BB', 'label' => 'Barbados'],
            ['value' => 'BY', 'label' => 'Belarus'],
            ['value' => 'BE', 'label' => 'Belgium'],
            ['value' => 'BZ', 'label' => 'Belize'],
            ['value' => 'BJ', 'label' => 'Benin'],
            ['value' => 'BM', 'label' => 'Bermuda'],
            ['value' => 'BT', 'label' => 'Bhutan'],
            ['value' => 'BO', 'label' => 'Bolivia'],
            ['value' => 'BA', 'label' => 'Bosnia and Herzegovina'],
            ['value' => 'BW', 'label' => 'Botswana'],
            ['value' => 'BR', 'label' => 'Brazil'],
            ['value' => 'IO', 'label' => 'British Indian Ocean Territory'],
            ['value' => 'BN', 'label' => 'Brunei'],
            ['value' => 'BG', 'label' => 'Bulgaria'],
            ['value' => 'BF', 'label' => 'Burkina Faso'],
            ['value' => 'BI', 'label' => 'Burundi'],
            ['value' => 'KH', 'label' => 'Cambodia'],
            ['value' => 'CM', 'label' => 'Cameroon'],
            ['value' => 'CA', 'label' => 'Canada'],
            ['value' => 'CV', 'label' => 'Cape Verde'],
            ['value' => 'KY', 'label' => 'Cayman Islands'],
            ['value' => 'CF', 'label' => 'Central African Republic'],
            ['value' => 'TD', 'label' => 'Chad'],
            ['value' => 'CL', 'label' => 'Chile'],
            ['value' => 'CN', 'label' => 'China'],
            ['value' => 'CX', 'label' => 'Christmas Island'],
            ['value' => 'CC', 'label' => 'Cocos (Keeling) Islands'],
            ['value' => 'CO', 'label' => 'Colombia'],
            ['value' => 'KM', 'label' => 'Comoros'],
            ['value' => 'CG', 'label' => 'Congo'],
            ['value' => 'CD', 'label' => 'Congo, Democratic Republic'],
            ['value' => 'CK', 'label' => 'Cook Islands'],
            ['value' => 'CR', 'label' => 'Costa Rica'],
            ['value' => 'CI', 'label' => 'Cote D\'Ivoire'],
            ['value' => 'HR', 'label' => 'Croatia'],
            ['value' => 'CU', 'label' => 'Cuba'],
            ['value' => 'CW', 'label' => 'Curacao'],
            ['value' => 'CY', 'label' => 'Cyprus'],
            ['value' => 'CZ', 'label' => 'Czech Republic'],
            ['value' => 'DK', 'label' => 'Denmark'],
            ['value' => 'DJ', 'label' => 'Djibouti'],
            ['value' => 'DM', 'label' => 'Dominica'],
            ['value' => 'DO', 'label' => 'Dominican Republic'],
            ['value' => 'EC', 'label' => 'Ecuador'],
            ['value' => 'EG', 'label' => 'Egypt'],
            ['value' => 'SV', 'label' => 'El Salvador'],
            ['value' => 'GQ', 'label' => 'Equatorial Guinea'],
            ['value' => 'ER', 'label' => 'Eritrea'],
            ['value' => 'EE', 'label' => 'Estonia'],
            ['value' => 'ET', 'label' => 'Ethiopia'],
            ['value' => 'FK', 'label' => 'Falkland Islands'],
            ['value' => 'FO', 'label' => 'Faroe Islands'],
            ['value' => 'FJ', 'label' => 'Fiji'],
            ['value' => 'FI', 'label' => 'Finland'],
            ['value' => 'FR', 'label' => 'France'],
            ['value' => 'GF', 'label' => 'French Guiana'],
            ['value' => 'PF', 'label' => 'French Polynesia'],
            ['value' => 'TF', 'label' => 'French Southern Territories'],
            ['value' => 'GA', 'label' => 'Gabon'],
            ['value' => 'GM', 'label' => 'Gambia'],
            ['value' => 'GE', 'label' => 'Georgia'],
            ['value' => 'DE', 'label' => 'Germany'],
            ['value' => 'GH', 'label' => 'Ghana'],
            ['value' => 'GI', 'label' => 'Gibraltar'],
            ['value' => 'GR', 'label' => 'Greece'],
            ['value' => 'GL', 'label' => 'Greenland'],
            ['value' => 'GD', 'label' => 'Grenada'],
            ['value' => 'IN', 'label' => 'India'],
            ['value' => 'US', 'label' => 'United States'],
            ['value' => 'UK', 'label' => 'United Kingdom'],
            ['value' => 'ZW', 'label' => 'Zimbabwe'],
        ];
    }
}
