<?php

declare(strict_types=1);

namespace App\Services;

class TimezoneService
{
    /**
     * Get a list of timezones with their UTC offsets and names.
     */
    public function getTimezones(): array
    {
        return [
            'UTC' => '(UTC+00:00) UTC',
            'Pacific/Midway' => '(UTC-11:00) Midway Island',
            'Pacific/Samoa' => '(UTC-11:00) Samoa',
            'Pacific/Honolulu' => '(UTC-10:00) Hawaii',
            'US/Alaska' => '(UTC-09:00) Alaska',
            'America/Los_Angeles' => '(UTC-08:00) Pacific Time (US & Canada)',
            'America/Tijuana' => '(UTC-08:00) Tijuana, Baja California',
            'US/Arizona' => '(UTC-07:00) Arizona',
            'America/Chihuahua' => '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
            'US/Mountain' => '(UTC-07:00) Mountain Time (US & Canada)',
            'America/Managua' => '(UTC-06:00) Central America',
            'US/Central' => '(UTC-06:00) Central Time (US & Canada)',
            'America/Mexico_City' => '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
            'Canada/Saskatchewan' => '(UTC-06:00) Saskatchewan',
            'America/Bogota' => '(UTC-05:00) Bogota, Lima, Quito',
            'US/Eastern' => '(UTC-05:00) Eastern Time (US & Canada)',
            'US/East-Indiana' => '(UTC-05:00) Indiana (East)',
            'Canada/Atlantic' => '(UTC-04:00) Atlantic Time (Canada)',
            'America/Caracas' => '(UTC-04:00) Caracas, La Paz',
            'America/Manaus' => '(UTC-04:00) Manaus',
            'America/Santiago' => '(UTC-04:00) Santiago',
            'Canada/Newfoundland' => '(UTC-03:30) Newfoundland',
            'America/Sao_Paulo' => '(UTC-03:00) Brasilia',
            'America/Argentina/Buenos_Aires' => '(UTC-03:00) Buenos Aires, Georgetown',
            'America/Godthab' => '(UTC-03:00) Greenland',
            'America/Montevideo' => '(UTC-03:00) Montevideo',
            'America/Noronha' => '(UTC-02:00) Mid-Atlantic',
            'Atlantic/Cape_Verde' => '(UTC-01:00) Cape Verde Is.',
            'Atlantic/Azores' => '(UTC-01:00) Azores',
            'Africa/Casablanca' => '(UTC+00:00) Casablanca, Monrovia, Reykjavik',
            'Europe/Dublin' => '(UTC+00:00) Dublin, Edinburgh, Lisbon, London',
            'Europe/Amsterdam' => '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
            'Europe/Belgrade' => '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
            'Europe/Brussels' => '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
            'Europe/Sarajevo' => '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
            'Africa/Lagos' => '(UTC+01:00) West Central Africa',
            'Asia/Amman' => '(UTC+02:00) Amman',
            'Europe/Athens' => '(UTC+02:00) Athens, Bucharest, Istanbul',
            'Asia/Beirut' => '(UTC+02:00) Beirut',
            'Africa/Cairo' => '(UTC+02:00) Cairo',
            'Africa/Harare' => '(UTC+02:00) Harare, Pretoria',
            'Europe/Helsinki' => '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
            'Asia/Jerusalem' => '(UTC+02:00) Jerusalem',
            'Europe/Minsk' => '(UTC+02:00) Minsk',
            'Africa/Windhoek' => '(UTC+02:00) Windhoek',
            'Asia/Kuwait' => '(UTC+03:00) Kuwait, Riyadh',
            'Europe/Moscow' => '(UTC+03:00) Moscow, St. Petersburg, Volgograd',
            'Africa/Nairobi' => '(UTC+03:00) Nairobi',
            'Asia/Tbilisi' => '(UTC+03:00) Tbilisi',
            'Asia/Tehran' => '(UTC+03:30) Tehran',
            'Asia/Muscat' => '(UTC+04:00) Abu Dhabi, Muscat',
            'Asia/Baku' => '(UTC+04:00) Baku',
            'Europe/Volgograd' => '(UTC+04:00) Volgograd',
            'Asia/Yerevan' => '(UTC+04:00) Yerevan',
            'Asia/Kabul' => '(UTC+04:30) Kabul',
            'Asia/Yekaterinburg' => '(UTC+05:00) Ekaterinburg',
            'Asia/Karachi' => '(UTC+05:00) Islamabad, Karachi, Tashkent',
            'Asia/Calcutta' => '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
            'Asia/Colombo' => '(UTC+05:30) Sri Jayawardenepura',
            'Asia/Katmandu' => '(UTC+05:45) Kathmandu',
            'Asia/Almaty' => '(UTC+06:00) Almaty, Novosibirsk',
            'Asia/Dhaka' => '(UTC+06:00) Astana, Dhaka',
            'Asia/Rangoon' => '(UTC+06:30) Yangon (Rangoon)',
            'Asia/Bangkok' => '(UTC+07:00) Bangkok, Hanoi, Jakarta',
            'Asia/Krasnoyarsk' => '(UTC+07:00) Krasnoyarsk',
            'Asia/Hong_Kong' => '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
            'Asia/Kuala_Lumpur' => '(UTC+08:00) Kuala Lumpur, Singapore',
            'Asia/Irkutsk' => '(UTC+08:00) Irkutsk, Ulaan Bataar',
            'Australia/Perth' => '(UTC+08:00) Perth',
            'Asia/Taipei' => '(UTC+08:00) Taipei',
            'Asia/Tokyo' => '(UTC+09:00) Osaka, Sapporo, Tokyo',
            'Asia/Seoul' => '(UTC+09:00) Seoul',
            'Asia/Yakutsk' => '(UTC+09:00) Yakutsk',
            'Australia/Adelaide' => '(UTC+09:30) Adelaide',
            'Australia/Darwin' => '(UTC+09:30) Darwin',
            'Australia/Brisbane' => '(UTC+10:00) Brisbane',
            'Australia/Canberra' => '(UTC+10:00) Canberra, Melbourne, Sydney',
            'Australia/Hobart' => '(UTC+10:00) Hobart',
            'Pacific/Guam' => '(UTC+10:00) Guam, Port Moresby',
            'Asia/Vladivostok' => '(UTC+10:00) Vladivostok',
            'Asia/Magadan' => '(UTC+11:00) Magadan, Solomon Is., New Caledonia',
            'Pacific/Auckland' => '(UTC+12:00) Auckland, Wellington',
            'Pacific/Fiji' => '(UTC+12:00) Fiji, Kamchatka, Marshall Is.',
            'Pacific/Tongatapu' => '(UTC+13:00) Nuku\'alofa',
        ];
    }
}
