<?php

declare(strict_types=1);

namespace Modules\MadrasaFunds\Services;

use App\Support\Facades\Hook;
use Illuminate\Support\Facades\DB;
use Modules\MadrasaFunds\Enums\Hooks\ReceiptActionHook;
use Modules\MadrasaFunds\Models\Receipt;

class ReceiptService
{
    /**
     * Create a new receipt. The receipt number is generated by the model.
     *
     * @param  array<string, mixed>  $data
     */
    public function create(array $data): Receipt
    {
        return DB::transaction(function () use ($data) {
            $data['created_by'] = $data['created_by'] ?? auth()->id();

            Hook::doAction(ReceiptActionHook::CREATED_BEFORE, $data);

            $receipt = Receipt::create($data);

            Hook::doAction(ReceiptActionHook::CREATED_AFTER, $receipt);

            return $receipt;
        });
    }

    /**
     * @param  array<string, mixed>  $data
     */
    public function update(Receipt $receipt, array $data): Receipt
    {
        $receipt->update($data);

        Hook::doAction(ReceiptActionHook::UPDATED_AFTER, $receipt);

        return $receipt;
    }

    public function cancel(Receipt $receipt, ?string $reason = null): Receipt
    {
        $receipt->update([
            'is_cancelled' => true,
            'cancelled_reason' => $reason,
        ]);

        Hook::doAction(ReceiptActionHook::CANCELLED_AFTER, $receipt);

        return $receipt;
    }

    public function delete(Receipt $receipt): void
    {
        $id = $receipt->id;
        $receipt->delete();

        Hook::doAction(ReceiptActionHook::DELETED_AFTER, $id);
    }
}
