/**
 * Default Block Definitions for LaraBuilder
 *
 * These blocks are available in all contexts unless filtered.
 */

// Default layout styles for all blocks
const defaultLayoutStyles = {
    margin: { top: '', right: '', bottom: '', left: '' },
    padding: { top: '', right: '', bottom: '', left: '' },
    width: '',
    minWidth: '',
    maxWidth: '',
    height: '',
    minHeight: '',
    maxHeight: '',
};

export const defaultBlocks = [
    {
        type: 'heading',
        label: 'Heading',
        category: 'Content',
        icon: 'mdi:format-header-1',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            text: 'Your Heading Here',
            level: 'h1',
            align: 'left',
            color: '#333333',
            fontSize: '32px',
            fontWeight: 'bold',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            colors: true,
            spacing: true,
            layout: true,
        },
    },
    {
        type: 'text',
        label: 'Text',
        category: 'Content',
        icon: 'mdi:format-text',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            content: 'Click to edit this text.',
            align: 'left',
            color: '#666666',
            fontSize: '16px',
            lineHeight: '1.6',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            colors: true,
            spacing: true,
            layout: true,
        },
    },
    {
        type: 'image',
        label: 'Image',
        category: 'Content',
        icon: 'mdi:image-outline',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            src: '',
            alt: 'Image description',
            width: '100%',
            height: 'auto',
            customWidth: '',
            customHeight: '',
            align: 'center',
            link: '',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            spacing: true,
            layout: true,
        },
    },
    {
        type: 'button',
        label: 'Button',
        category: 'Content',
        icon: 'mdi:button-cursor',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            text: 'Click Here',
            link: '#',
            backgroundColor: '#635bff',
            textColor: '#ffffff',
            borderRadius: '6px',
            padding: '12px 24px',
            align: 'center',
            fontSize: '16px',
            fontWeight: '600',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            colors: true,
            spacing: true,
            layout: true,
        },
    },
    {
        type: 'social',
        label: 'Social',
        category: 'Content',
        icon: 'mdi:share-variant-outline',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            align: 'center',
            iconSize: '32px',
            gap: '12px',
            links: {
                facebook: '',
                twitter: '',
                instagram: '',
                linkedin: '',
                youtube: '',
            },
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            layout: true,
        },
    },
    {
        type: 'divider',
        label: 'Divider',
        category: 'Layout',
        icon: 'mdi:minus',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            style: 'solid',
            color: '#e5e7eb',
            thickness: '1px',
            width: '100%',
            margin: '20px 0',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            colors: true,
            spacing: true,
            layout: true,
        },
    },
    {
        type: 'spacer',
        label: 'Spacer',
        category: 'Layout',
        icon: 'mdi:arrow-expand-vertical',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            height: '40px',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            spacing: true,
            layout: true,
        },
    },
    {
        type: 'columns',
        label: 'Columns',
        category: 'Layout',
        icon: 'mdi:view-column-outline',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            columns: 1,
            gap: '20px',
            children: [[]],
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            spacing: true,
            nesting: true,
            layout: true,
        },
    },
    {
        type: 'html',
        label: 'HTML',
        category: 'Advanced',
        icon: 'mdi:code-tags',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            code: '<div style="padding: 20px; text-align: center;">Custom HTML content</div>',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            layout: true,
        },
    },
    {
        type: 'quote',
        label: 'Quote',
        category: 'Content',
        icon: 'mdi:format-quote-close',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            text: 'This is a quote or testimonial that stands out from the rest of the content.',
            author: 'John Doe',
            authorTitle: 'CEO, Company',
            borderColor: '#635bff',
            backgroundColor: '#f8fafc',
            textColor: '#475569',
            authorColor: '#1e293b',
            align: 'left',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            colors: true,
            layout: true,
        },
    },
    {
        type: 'list',
        label: 'List',
        category: 'Content',
        icon: 'mdi:format-list-bulleted',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            items: ['First item in the list', 'Second item in the list', 'Third item in the list'],
            listType: 'bullet',
            color: '#333333',
            fontSize: '16px',
            iconColor: '#635bff',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            colors: true,
            layout: true,
        },
    },
    {
        type: 'video',
        label: 'Video',
        category: 'Content',
        icon: 'mdi:play-circle-outline',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            thumbnailUrl: '',
            videoUrl: '',
            alt: 'Video thumbnail',
            width: '100%',
            align: 'center',
            playButtonColor: '',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            layout: true,
        },
    },
    {
        type: 'footer',
        label: 'Footer',
        category: 'Layout',
        icon: 'mdi:page-layout-footer',
        contexts: ['email', 'campaign'],
        defaultProps: {
            companyName: 'Your Company Name',
            address: '123 Street Name, City, Country',
            phone: '+1 234 567 890',
            email: 'contact@company.com',
            unsubscribeText: 'Unsubscribe from these emails',
            unsubscribeUrl: '#unsubscribe',
            copyright: '© 2024 Your Company. All rights reserved.',
            textColor: '#6b7280',
            linkColor: '#635bff',
            fontSize: '12px',
            align: 'center',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            colors: true,
            layout: true,
        },
    },
    {
        type: 'countdown',
        label: 'Countdown',
        category: 'Advanced',
        icon: 'mdi:timer-outline',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            targetDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
            targetTime: '23:59',
            title: 'Sale Ends In',
            backgroundColor: '#1e293b',
            textColor: '#ffffff',
            numberColor: '#635bff',
            align: 'center',
            expiredMessage: 'This offer has expired!',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            colors: true,
            layout: true,
        },
    },
    {
        type: 'table',
        label: 'Table',
        category: 'Advanced',
        icon: 'mdi:table',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            headers: ['Product', 'Qty', 'Price'],
            rows: [
                ['Product Name 1', '2', '$29.99'],
                ['Product Name 2', '1', '$49.99'],
            ],
            showHeader: true,
            headerBgColor: '#f1f5f9',
            headerTextColor: '#1e293b',
            borderColor: '#e2e8f0',
            cellPadding: '12px',
            fontSize: '14px',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            colors: true,
            layout: true,
        },
    },
    {
        type: 'code',
        label: 'Code',
        category: 'Advanced',
        icon: 'mdi:code-braces',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            code: '<?php echo "hello"; ?>',
            fontSize: '14px',
            backgroundColor: '#1e1e1e',
            textColor: '#d4d4d4',
            borderRadius: '8px',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            colors: true,
            layout: true,
        },
    },
    {
        type: 'markdown',
        label: 'Markdown',
        category: 'Advanced',
        icon: 'mdi:language-markdown',
        contexts: ['page'],
        defaultProps: {
            url: '',
            showSource: true,
            cacheEnabled: true,
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            layout: true,
        },
    },
    {
        type: 'preformatted',
        label: 'Preformatted',
        category: 'Content',
        icon: 'mdi:format-text-wrapping-wrap',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            text: 'Write preformatted text...',
            fontSize: '14px',
            backgroundColor: '#f5f5f5',
            textColor: '#333333',
            borderColor: '#e0e0e0',
            borderRadius: '4px',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            colors: true,
            layout: true,
        },
    },
    {
        type: 'text-editor',
        label: 'Text Editor',
        category: 'Content',
        icon: 'mdi:text-box-edit-outline',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            content: '',
            align: 'left',
            color: '#333333',
            fontSize: '16px',
            lineHeight: '1.6',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            align: true,
            colors: true,
            spacing: true,
            layout: true,
        },
    },
    {
        type: 'accordion',
        label: 'Accordion',
        category: 'Content',
        icon: 'mdi:arrow-collapse-vertical',
        contexts: ['email', 'page', 'campaign'],
        defaultProps: {
            items: [
                { title: 'Accordion Item 1', content: 'Content for the first accordion item. Click to expand and see more details.' },
                { title: 'Accordion Item 2', content: 'Content for the second accordion item. You can add as many items as you need.' },
            ],
            // Behavior
            independentToggle: false,
            transitionDuration: 200,
            // Header styles
            headerBgColor: '#ffffff',
            headerBgColorActive: '#f9fafb',
            headerPadding: '16px',
            titleColor: '#1f2937',
            titleFontSize: '16px',
            titleFontWeight: '600',
            // Content styles
            contentBgColor: '#ffffff',
            contentColor: '#4b5563',
            contentFontSize: '14px',
            contentPadding: '16px',
            // Icon
            iconColor: '#6b7280',
            iconPosition: 'right',
            // Border
            borderColor: '#e5e7eb',
            borderRadius: '8px',
            layoutStyles: { ...defaultLayoutStyles },
        },
        supports: {
            colors: true,
            layout: true,
        },
    },
];

// Export the default layout styles for use in other modules
export { defaultLayoutStyles };
export default defaultBlocks;
